ALTER TABLE "categories" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "lendings" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "locations" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "profiles" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "Users can view their own categories" ON "categories" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) is not null and (select auth.uid()) = "categories"."user_id");--> statement-breakpoint
CREATE POLICY "Users can create their own categories" ON "categories" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.uid()) is not null and (select auth.uid()) = "categories"."user_id");--> statement-breakpoint
CREATE POLICY "Users can update their own categories" ON "categories" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.uid()) is not null and (select auth.uid()) = "categories"."user_id") WITH CHECK ((select auth.uid()) is not null and (select auth.uid()) = "categories"."user_id");--> statement-breakpoint
CREATE POLICY "Users can delete their own categories" ON "categories" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((select auth.uid()) is not null and (select auth.uid()) = "categories"."user_id");--> statement-breakpoint
CREATE POLICY "Users can view their own items" ON "items" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) is not null and (select auth.uid()) = "items"."user_id");--> statement-breakpoint
CREATE POLICY "Users can create their own items" ON "items" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.uid()) is not null and (select auth.uid()) = "items"."user_id");--> statement-breakpoint
CREATE POLICY "Users can update their own items" ON "items" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.uid()) is not null and (select auth.uid()) = "items"."user_id") WITH CHECK ((select auth.uid()) is not null and (select auth.uid()) = "items"."user_id");--> statement-breakpoint
CREATE POLICY "Users can delete their own items" ON "items" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((select auth.uid()) is not null and (select auth.uid()) = "items"."user_id");--> statement-breakpoint
CREATE POLICY "Users can view their own lendings" ON "lendings" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) is not null and (select auth.uid()) = "lendings"."user_id");--> statement-breakpoint
CREATE POLICY "Users can create their own lendings" ON "lendings" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.uid()) is not null and (select auth.uid()) = "lendings"."user_id");--> statement-breakpoint
CREATE POLICY "Users can update their own lendings" ON "lendings" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.uid()) is not null and (select auth.uid()) = "lendings"."user_id") WITH CHECK ((select auth.uid()) is not null and (select auth.uid()) = "lendings"."user_id");--> statement-breakpoint
CREATE POLICY "Users can delete their own lendings" ON "lendings" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((select auth.uid()) is not null and (select auth.uid()) = "lendings"."user_id");--> statement-breakpoint
CREATE POLICY "Users can view their own locations" ON "locations" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) is not null and (select auth.uid()) = "locations"."user_id");--> statement-breakpoint
CREATE POLICY "Users can create their own locations" ON "locations" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.uid()) is not null and (select auth.uid()) = "locations"."user_id");--> statement-breakpoint
CREATE POLICY "Users can update their own locations" ON "locations" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.uid()) is not null and (select auth.uid()) = "locations"."user_id") WITH CHECK ((select auth.uid()) is not null and (select auth.uid()) = "locations"."user_id");--> statement-breakpoint
CREATE POLICY "Users can delete their own locations" ON "locations" AS PERMISSIVE FOR DELETE TO "authenticated" USING ((select auth.uid()) is not null and (select auth.uid()) = "locations"."user_id");--> statement-breakpoint
CREATE POLICY "Users can view their own profile" ON "profiles" AS PERMISSIVE FOR SELECT TO "authenticated" USING ((select auth.uid()) is not null and (select auth.uid()) = "profiles"."id");--> statement-breakpoint
CREATE POLICY "Users can create their own profile" ON "profiles" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK ((select auth.uid()) is not null and (select auth.uid()) = "profiles"."id");--> statement-breakpoint
CREATE POLICY "Users can update their own profile" ON "profiles" AS PERMISSIVE FOR UPDATE TO "authenticated" USING ((select auth.uid()) is not null and (select auth.uid()) = "profiles"."id") WITH CHECK ((select auth.uid()) is not null and (select auth.uid()) = "profiles"."id");